module.exports = {
  darkMode: 'class',
  content: [
    './public/**/*.html',
    './public/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#2563EB',
        'primary-dark': '#1D4ED8',
        'primary-hover': '#1d4ed8',
        'primary-light': '#EFF6FF',
        secondary: '#006e37',
        'background-light': '#F8FAFC',
        'background-dark': '#0F172A',
        'surface-light': '#FFFFFF',
        'surface-dark': '#1E293B',
        'text-light': '#1F2937',
        'text-dark': '#D1D5DB',
        'text-main-light': '#1F2937',
        'text-main-dark': '#F3F4F6',
        'text-muted-light': '#6B7280',
        'text-muted-dark': '#9CA3AF',
        'border-light': '#E5E7EB',
        'border-dark': '#374151',
        'success-light': '#D1FAE5',
        'success-dark': '#064E3B',
        'warning-light': '#FEF3C7',
        'warning-dark': '#78350F',
        'danger-light': '#FFE4E6',
        'danger-dark': '#7F1D1D',
        surface: '#f8f9fa',
        'on-surface': '#2d3335',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f5',
        'surface-container-high': '#e5e9eb',
        'on-surface-variant': '#5a6062',
        'outline-variant': '#adb3b5',
        error: '#a83836',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Manrope', 'Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        xl: '1rem',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/container-queries'),
  ],
};
